//! Implemented visualization modes (Waves 1-6 of `docs/VIZ_MASTER_PLAN.md`).

pub mod alien_vision;
pub mod aurora;
pub mod basin_map;
pub mod blueprint;
pub mod braid;
pub mod bullet_time;
pub mod celestial_atlas;
pub mod chandelier;
pub mod chord_progression;
pub mod chrono_grid;
pub mod comet;
pub mod corotating;
pub mod depth_pack;
pub mod dust_nebula;
pub mod dwell_nebula;
pub mod editorial_retime;
pub mod ephemeris_poster;
pub mod epicycles;
pub mod epilogue;
pub mod field_lines;
pub mod frost;
pub mod galaxy_collision;
pub mod gw_chirp;
pub mod hologram;
pub mod hyperspectral_flythrough;
pub mod lensing;
pub mod light_echoes;
pub mod lightning;
pub mod marbling;
pub mod medial_recursion;
pub mod mission_control;
pub mod multiverse;
pub mod neon;
pub mod oscilloscope;
pub mod physarum;
pub mod plotter_svg;
pub mod prism_portrait;
pub mod reconnection;
pub mod recurrence;
pub mod retarded_time;
pub mod ride_along;
pub mod roche;
pub mod sculpture_export;
pub mod shape_sphere;
pub mod slit_scan;
pub mod sonification;
pub mod spectral_centroid;
pub mod spectrum_card;
pub mod strobe;
pub mod syzygy_wheel;
pub mod terra;
pub mod thin_film;
pub mod three_shadows;
pub mod tilt;
pub mod topo_contours;
pub mod trailer;
pub mod triangle_centers;
pub mod turntable;
pub mod webgl_viewer;
pub mod winding_glass;
pub mod worldtube;

use crate::viz::VizMode;

/// Instantiate the implementation for a catalog flag, if one exists.
#[must_use]
pub fn build(flag: &str) -> Option<Box<dyn VizMode>> {
    match flag {
        "alien-vision" => Some(Box::new(alien_vision::AlienVision)),
        "spectral-centroid" => Some(Box::new(spectral_centroid::SpectralCentroid)),
        "prism-portrait" => Some(Box::new(prism_portrait::PrismPortrait)),
        "spectrum-card" => Some(Box::new(spectrum_card::SpectrumCard)),
        "thin-film" => Some(Box::new(thin_film::ThinFilm)),
        "braid" => Some(Box::new(braid::Braid)),
        "gw-chirp" => Some(Box::new(gw_chirp::GwChirp)),
        "syzygy-wheel" => Some(Box::new(syzygy_wheel::SyzygyWheel)),
        "triangle-centers" => Some(Box::new(triangle_centers::TriangleCenters)),
        "medial-recursion" => Some(Box::new(medial_recursion::MedialRecursion)),
        "chrono-grid" => Some(Box::new(chrono_grid::ChronoGrid)),
        "slit-scan" => Some(Box::new(slit_scan::SlitScan)),
        "strobe" => Some(Box::new(strobe::Strobe)),
        "comet" => Some(Box::new(comet::Comet)),
        "three-shadows" => Some(Box::new(three_shadows::ThreeShadows)),
        "ride-along" => Some(Box::new(ride_along::RideAlong)),
        "retarded-time" => Some(Box::new(retarded_time::RetardedTime)),
        "winding-glass" => Some(Box::new(winding_glass::WindingGlass)),
        "plotter-svg" => Some(Box::new(plotter_svg::PlotterSvg)),
        "oscilloscope" => Some(Box::new(oscilloscope::Oscilloscope)),
        "turntable" => Some(Box::new(turntable::Turntable)),
        "dwell-nebula" => Some(Box::new(dwell_nebula::DwellNebula)),
        "topo-contours" => Some(Box::new(topo_contours::TopoContours)),
        "depth-pack" => Some(Box::new(depth_pack::DepthPack)),
        "field-lines" => Some(Box::new(field_lines::FieldLines)),
        "corotating" => Some(Box::new(corotating::Corotating)),
        "lensing" => Some(Box::new(lensing::Lensing)),
        "roche" => Some(Box::new(roche::Roche)),
        "reconnection" => Some(Box::new(reconnection::Reconnection)),
        "dust-nebula" => Some(Box::new(dust_nebula::DustNebula)),
        "galaxy-collision" => Some(Box::new(galaxy_collision::GalaxyCollision)),
        "physarum" => Some(Box::new(physarum::Physarum)),
        "frost" => Some(Box::new(frost::Frost)),
        "lightning" => Some(Box::new(lightning::Lightning)),
        "marbling" => Some(Box::new(marbling::Marbling)),
        "light-echoes" => Some(Box::new(light_echoes::LightEchoes)),
        "worldtube" => Some(Box::new(worldtube::Worldtube)),
        "hyperspectral-flythrough" => {
            Some(Box::new(hyperspectral_flythrough::HyperspectralFlythrough))
        }
        "shape-sphere" => Some(Box::new(shape_sphere::ShapeSphere)),
        "aurora" => Some(Box::new(aurora::Aurora)),
        "neon" => Some(Box::new(neon::Neon)),
        "chandelier" => Some(Box::new(chandelier::Chandelier)),
        "sculpture-export" => Some(Box::new(sculpture_export::SculptureExport)),
        "bullet-time" => Some(Box::new(bullet_time::BulletTime)),
        "epilogue" => Some(Box::new(epilogue::Epilogue)),
        "multiverse" => Some(Box::new(multiverse::Multiverse)),
        "editorial-retime" => Some(Box::new(editorial_retime::EditorialRetime)),
        "basin-map" => Some(Box::new(basin_map::BasinMap)),
        "terra" => Some(Box::new(terra::Terra)),
        "sonification" => Some(Box::new(sonification::Sonification)),
        "chord-progression" => Some(Box::new(chord_progression::ChordProgression)),
        "epicycles" => Some(Box::new(epicycles::Epicycles)),
        "recurrence" => Some(Box::new(recurrence::Recurrence)),
        "mission-control" => Some(Box::new(mission_control::MissionControl)),
        "ephemeris-poster" => Some(Box::new(ephemeris_poster::EphemerisPoster)),
        "blueprint" => Some(Box::new(blueprint::Blueprint)),
        "webgl-viewer" => Some(Box::new(webgl_viewer::WebglViewer)),
        "tilt" => Some(Box::new(tilt::Tilt)),
        "hologram" => Some(Box::new(hologram::Hologram)),
        "trailer" => Some(Box::new(trailer::Trailer)),
        "celestial-atlas" => Some(Box::new(celestial_atlas::CelestialAtlas)),
        _ => None,
    }
}
