# Maximum width of each line. The default is 100.
max_width = 100

# Use small heuristics for formatting.
# The default is "Default". Options are "Default", "Max", "Off".
use_small_heuristics = "Max"

# Use tabs for indentation. The default is false.
hard_tabs = false

# Indent size. The default is 4.
tab_spaces = 4
