//! Orbit statistics card — a beautifully designed SVG data card showing
//! chaos score, equilateralness, Borda rank, active effects, and color swatches.

use crate::render::randomizable_config::ResolvedEffectConfig;
use crate::sim::TrajectoryResult;
use std::io::Write;
use tracing::info;

pub struct StatsCardData<'a> {
    pub seed: &'a str,
    pub result: &'a TrajectoryResult,
    pub config: &'a ResolvedEffectConfig,
    pub num_sims: usize,
    pub num_steps: usize,
}

pub fn generate_stats_card(
    data: &StatsCardData<'_>,
    output_path: &str,
) -> Result<(), Box<dyn std::error::Error>> {
    info!("Generating orbit statistics card...");

    let active_effects = collect_active_effects(data.config);
    let survival_rate =
        (data.num_sims - data.result.discarded_count) as f64 / data.num_sims as f64 * 100.0;

    let metrics_section = build_metrics_svg(data);
    let effects_section = build_effects_svg(&active_effects);
    let seed_display = truncate_seed(data.seed);

    let svg = format!(
        r###"<?xml version="1.0" encoding="UTF-8"?>
<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 600 900" width="600" height="900">
  <defs>
    <linearGradient id="bg" x1="0" y1="0" x2="0" y2="1">
      <stop offset="0%" stop-color="#0D0521"/>
      <stop offset="100%" stop-color="#1A0B3E"/>
    </linearGradient>
    <linearGradient id="accent" x1="0" y1="0" x2="1" y2="0">
      <stop offset="0%" stop-color="#6C3CE1"/>
      <stop offset="100%" stop-color="#00D4AA"/>
    </linearGradient>
  </defs>
  <rect width="600" height="900" fill="url(#bg)" rx="16"/>
  <rect x="30" y="30" width="540" height="4" fill="url(#accent)" rx="2"/>
  <text x="300" y="80" text-anchor="middle" fill="#F0EDFF" font-family="monospace" font-size="14"
        letter-spacing="4">COSMIC SIGNATURE</text>
  <text x="300" y="115" text-anchor="middle" fill="#6C3CE1" font-family="monospace" font-size="12"
        letter-spacing="2">0x{seed}</text>
  <rect x="30" y="140" width="540" height="1" fill="#2A1854" />
  {metrics}
  <rect x="30" y="500" width="540" height="1" fill="#2A1854" />
  <text x="45" y="530" fill="#8B7BAA" font-family="monospace" font-size="11"
        letter-spacing="2">ACTIVE EFFECTS</text>
  {effects}
  <rect x="30" y="740" width="540" height="1" fill="#2A1854" />
  <text x="45" y="770" fill="#8B7BAA" font-family="monospace" font-size="11"
        letter-spacing="2">SIMULATION</text>
  <text x="45" y="800" fill="#F0EDFF" font-family="monospace" font-size="13">
    Orbits tested: {nsims:>8}  |  Steps: {nsteps}</text>
  <text x="45" y="825" fill="#F0EDFF" font-family="monospace" font-size="13">
    Survival rate: {surv:.1}%  |  Selected: #{sel}</text>
  <rect x="30" y="856" width="540" height="4" fill="url(#accent)" rx="2" opacity="0.5"/>
  <text x="300" y="885" text-anchor="middle" fill="#4A3A6A" font-family="monospace"
        font-size="10">generated by three_body_problem</text>
</svg>"###,
        seed = seed_display,
        metrics = metrics_section,
        effects = effects_section,
        nsims = data.num_sims,
        nsteps = data.num_steps,
        surv = survival_rate,
        sel = data.result.selected_index,
    );

    let mut file = std::fs::File::create(output_path)?;
    file.write_all(svg.as_bytes())?;
    info!("   Saved stats card => {}", output_path);
    Ok(())
}

fn truncate_seed(seed: &str) -> String {
    let clean = seed.strip_prefix("0x").unwrap_or(seed);
    if clean.len() > 16 {
        format!("{}...{}", &clean[..8], &clean[clean.len() - 8..])
    } else {
        clean.to_string()
    }
}

fn build_metrics_svg(data: &StatsCardData<'_>) -> String {
    let metrics: Vec<(&str, f64, usize)> = vec![
        ("CHAOS SCORE", data.result.chaos, data.result.chaos_pts),
        ("EQUILATERALNESS", data.result.equilateralness, data.result.equil_pts),
    ];

    let mut svg = String::new();
    let mut y = 180i32;

    for (label, value, pts) in &metrics {
        let bar_width = (*value).clamp(0.0, 1.0) * 480.0;
        let by = y + 10;
        let ty = y + 28;
        let py = y + 55;
        svg.push_str(&format!(
            concat!(
                "  <text x=\"45\" y=\"{}\" fill=\"#8B7BAA\" font-family=\"monospace\"",
                " font-size=\"11\" letter-spacing=\"2\">{}</text>\n",
                "  <rect x=\"45\" y=\"{}\" width=\"480\" height=\"24\" fill=\"#1A0B3E\"",
                " stroke=\"#2A1854\" rx=\"4\"/>\n",
                "  <rect x=\"45\" y=\"{}\" width=\"{:.0}\" height=\"24\" fill=\"#6C3CE1\"",
                " opacity=\"0.6\" rx=\"4\"/>\n",
                "  <text x=\"535\" y=\"{}\" text-anchor=\"end\" fill=\"#F0EDFF\"",
                " font-family=\"monospace\" font-size=\"13\">{:.4}</text>\n",
                "  <text x=\"45\" y=\"{}\" fill=\"#4A3A6A\" font-family=\"monospace\"",
                " font-size=\"10\">Borda points: {}</text>\n",
            ),
            y, label, by, by, bar_width, ty, value, py, pts,
        ));
        y += 80;
    }

    svg.push_str(&format!(
        concat!(
            "  <text x=\"45\" y=\"{}\" fill=\"#8B7BAA\" font-family=\"monospace\"",
            " font-size=\"11\" letter-spacing=\"2\">WEIGHTED BORDA SCORE</text>\n",
            "  <text x=\"45\" y=\"{}\" fill=\"#00D4AA\" font-family=\"monospace\"",
            " font-size=\"28\">{:.3}</text>\n",
        ),
        y,
        y + 40,
        data.result.total_score_weighted,
    ));

    svg
}

fn build_effects_svg(effects: &[&str]) -> String {
    let mut svg = String::new();
    let cols = 2;
    let col_width = 260;

    for (i, effect) in effects.iter().enumerate() {
        let col = i % cols;
        let row = i / cols;
        let x = 45 + col * col_width;
        let y = 555 + row * 25;
        svg.push_str(&format!(
            concat!(
                "  <circle cx=\"{}\" cy=\"{}\" r=\"4\" fill=\"#6C3CE1\"/>\n",
                "  <text x=\"{}\" y=\"{}\" fill=\"#F0EDFF\" font-family=\"monospace\"",
                " font-size=\"12\">{}</text>\n",
            ),
            x,
            y - 4,
            x + 12,
            y,
            effect,
        ));
    }
    svg
}

#[cfg(test)]
mod tests {
    use super::*;

    fn make_result() -> TrajectoryResult {
        TrajectoryResult {
            chaos: 0.42,
            equilateralness: 0.78,
            chaos_pts: 30,
            equil_pts: 55,
            total_score: 85,
            total_score_weighted: 12.345,
            selected_index: 7,
            discarded_count: 900,
        }
    }

    fn make_config_all_off() -> ResolvedEffectConfig {
        ResolvedEffectConfig {
            width: 1920,
            height: 1080,
            enable_bloom: false,
            enable_glow: false,
            enable_chromatic_bloom: false,
            enable_perceptual_blur: false,
            enable_micro_contrast: false,
            enable_gradient_map: false,
            enable_color_grade: false,
            enable_champleve: false,
            enable_aether: false,
            enable_opalescence: false,
            enable_edge_luminance: false,
            enable_atmospheric_depth: false,
            enable_fine_texture: false,
            nebula_strength: 0.0,
            blur_strength: 0.0, blur_radius_scale: 0.0, blur_core_brightness: 0.0,
            dog_strength: 0.0, dog_sigma_scale: 0.0, dog_ratio: 0.0,
            glow_strength: 0.0, glow_threshold: 0.0, glow_radius_scale: 0.0,
            glow_sharpness: 0.0, glow_saturation_boost: 0.0,
            chromatic_bloom_strength: 0.0, chromatic_bloom_radius_scale: 0.0,
            chromatic_bloom_separation_scale: 0.0, chromatic_bloom_threshold: 0.0,
            perceptual_blur_strength: 0.0, color_grade_strength: 0.0,
            vignette_strength: 0.0, vignette_softness: 0.0, vibrance: 0.0,
            clarity_strength: 0.0, tone_curve_strength: 0.0,
            gradient_map_strength: 0.0, gradient_map_hue_preservation: 0.0, gradient_map_palette: 0,
            opalescence_strength: 0.0, opalescence_scale: 0.0, opalescence_layers: 0,
            champleve_flow_alignment: 0.0, champleve_interference_amplitude: 0.0,
            champleve_rim_intensity: 0.0, champleve_rim_warmth: 0.0, champleve_interior_lift: 0.0,
            aether_flow_alignment: 0.0, aether_scattering_strength: 0.0,
            aether_iridescence_amplitude: 0.0, aether_caustic_strength: 0.0,
            micro_contrast_strength: 0.0, micro_contrast_radius: 0,
            edge_luminance_strength: 0.0, edge_luminance_threshold: 0.0,
            edge_luminance_brightness_boost: 0.0,
            atmospheric_depth_strength: 0.0, atmospheric_desaturation: 0.0,
            atmospheric_darkening: 0.0,
            atmospheric_fog_color_r: 0.0, atmospheric_fog_color_g: 0.0, atmospheric_fog_color_b: 0.0,
            fine_texture_strength: 0.0, fine_texture_scale: 0.0, fine_texture_contrast: 0.0,
            hdr_scale: 0.0, clip_black: 0.0, clip_white: 1.0,
            nebula_octaves: 0, nebula_base_frequency: 0.0,
        }
    }

    #[test]
    fn test_truncate_seed_short() {
        assert_eq!(truncate_seed("abcdef"), "abcdef");
        assert_eq!(truncate_seed("0xabcdef"), "abcdef");
    }

    #[test]
    fn test_truncate_seed_long() {
        let long = "0x1234567890abcdef1234567890abcdef";
        let result = truncate_seed(long);
        assert!(result.contains("..."));
        assert!(result.starts_with("12345678"));
        assert!(result.ends_with("90abcdef"));
    }

    #[test]
    fn test_truncate_seed_exactly_16() {
        assert_eq!(truncate_seed("1234567890abcdef"), "1234567890abcdef");
    }

    #[test]
    fn test_collect_active_effects_all_off() {
        let config = make_config_all_off();
        assert!(collect_active_effects(&config).is_empty());
    }

    #[test]
    fn test_collect_active_effects_all_on() {
        let mut config = make_config_all_off();
        config.enable_bloom = true;
        config.enable_glow = true;
        config.enable_chromatic_bloom = true;
        config.enable_perceptual_blur = true;
        config.enable_micro_contrast = true;
        config.enable_gradient_map = true;
        config.enable_color_grade = true;
        config.enable_opalescence = true;
        config.enable_champleve = true;
        config.enable_aether = true;
        config.enable_edge_luminance = true;
        config.enable_atmospheric_depth = true;
        config.enable_fine_texture = true;
        config.nebula_strength = 0.5;
        assert_eq!(collect_active_effects(&config).len(), 14);
    }

    #[test]
    fn test_build_metrics_svg_contains_score() {
        let result = make_result();
        let config = make_config_all_off();
        let data = StatsCardData {
            seed: "0xCAFE",
            result: &result,
            config: &config,
            num_sims: 1000,
            num_steps: 500_000,
        };
        let svg = build_metrics_svg(&data);
        assert!(svg.contains("12.345"), "should contain the weighted Borda score");
        assert!(svg.contains("CHAOS SCORE"));
        assert!(svg.contains("EQUILATERALNESS"));
    }

    #[test]
    fn test_build_effects_svg_lists_effects() {
        let effects = vec!["DoG Bloom", "Aether Weave"];
        let svg = build_effects_svg(&effects);
        assert!(svg.contains("DoG Bloom"));
        assert!(svg.contains("Aether Weave"));
    }
}

fn collect_active_effects(config: &ResolvedEffectConfig) -> Vec<&'static str> {
    let mut effects = Vec::new();
    if config.enable_bloom { effects.push("DoG Bloom"); }
    if config.enable_glow { effects.push("Glow Enhancement"); }
    if config.enable_chromatic_bloom { effects.push("Chromatic Bloom"); }
    if config.enable_perceptual_blur { effects.push("Perceptual Blur"); }
    if config.enable_micro_contrast { effects.push("Micro Contrast"); }
    if config.enable_gradient_map { effects.push("Gradient Map"); }
    if config.enable_color_grade { effects.push("Color Grade"); }
    if config.enable_opalescence { effects.push("Opalescence"); }
    if config.enable_champleve { effects.push("Champlevé"); }
    if config.enable_aether { effects.push("Aether Weave"); }
    if config.enable_edge_luminance { effects.push("Edge Luminance"); }
    if config.enable_atmospheric_depth { effects.push("Atmospheric Depth"); }
    if config.enable_fine_texture { effects.push("Fine Texture"); }
    if config.nebula_strength > 0.0 { effects.push("Nebula Clouds"); }
    effects
}
